# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d762f58abd3367a365ffc39fe414b4fe61cbf2199d4c8e0f9d7ac7e75370c73bda78ac77b86951827b07b9f91c48d2c0ce813adf7df9370e202524154453e1

test:
  secret_key_base: 7e59f864eac8437791946ad285694945c6e00ed334321b6bebefedc143b04e80a59bae8667f99d2842029bac4cda8f637e74a3b1a8b3d72b9779c640f677e041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
